name: Release

on:
  push:
    branches:
      - prerelease

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  pre-release:
    name: Changesets Prerelease
    if: github.repository == 'udittyagi/turborepo-changeset'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: yarn

      - name: Check for pre.json file existence
        id: check_files
        uses: andstor/file-existence-action@v3.0.0
        with:
          files: ".changeset/pre.json"

      - name: Enter prerelease mode (bet by default)
        # If .changeset/pre.json does not exist and we did not recently exit
        # prerelease mode, enter prerelease mode with tag beta
        if: steps.check_files.outputs.files_exists == 'false' && !contains(github.event.head_commit.message, 'Exit prerelease')
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          yarn run changeset pre enter beta
          git add -A
          git commit -m 'Enter prerelease mode'
          git push
          echo "Take a pull and then push again as you were not in the pre release mode"

      - name: Create prerelease PR
        # If .changeset/pre.json exists and we are not currently cutting a
        # release after merging a Version Packages PR
        if: steps.check_files.outputs.files_exists == 'true' && !startsWith(github.event.head_commit.message, 'Version Packages')
        uses: changesets/action@v1
        with:
          version: yarn changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm + GitHub
        id: changesets
        # Only run publish if we're still in pre mode and the last commit was
        # via an automatically created Version Packages PR
        if: steps.check_files.outputs.files_exists == 'true' && startsWith(github.event.head_commit.message, 'Version Packages')
        uses: changesets/action@v1
        with:
          version: echo "This step should never version"
          publish: yarn release # by default, this will publish to npm and GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
